# Generated by Django 5.2.5 on 2025-08-27 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scanhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='user',
        ),
        migrations.CreateModel(
            name='WasteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('Organic', 'Organic'), ('Recyclable', 'Recyclable'), ('Hazardous', 'Hazardous'), ('Other', 'Other')], default='Other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ScanHistory',
        ),
        migrations.DeleteModel(
            name='WasteItem',
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
